#!/usr/bin/env bash
# prints number 1-20 using while loop and case statement
#"bad luck from China" 4th iter
#"bad luck from Japan" 9th iter
#"bad luck from Italy" 17th iter

N="1"
while [ "$N" -le "20" ]; do
	echo "$N"

	case "$N" in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	let "N++"
done
